import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from './contexts/AuthContext';
import ClientLayout from './components/clientLayout';
import "./globals.css";

// Font configuration for the application, using Geist Sans and Geist Mono fonts.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata export for the application's title and description.
export const metadata = {
  title: "Capstone Project",
  description: "Generated by create next app.",
};

// Separate export for viewport configuration to ensure proper scaling on different devices.
export const viewport = {
  width: "device-width",
  initialScale: 1,
};

// Root layout component that wraps the entire application structure.
export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Meta tag to define viewport settings for responsive design. */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* AuthProvider ensures authentication context is available throughout the application. */}
        <AuthProvider>
          {/* ClientLayout handles the client-side layout structure. */}
          <ClientLayout>{children}</ClientLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
